### ISSUE TITLE
Recherche sur les logiciels existant pour l'IB et l'IHM

### ISSUE THREAD

**Issue by Devotron** [Devotron/ProjetSynergieIB-IHM#3]

**Comment by niteka** [comment]
[outil.pdf](https://github.com/Devotron/ProjetSynergieIB-IHM/files/797910/outil.pdf)
[outil.pdf](https://github.com/Devotron/ProjetSynergieIB-IHM/files/797913/outil.pdf)

**Comment by niteka** [comment]
# OpenOME
En tant qu'application autonome et en tant que plug-in pour d'autres outils populaires, comme Eclipse et Protégé, OpenOME est conçu pour être un outil de modélisation et d'analyse axé sur les buts et / ou les agents.

# OME
Un éditeur de graphes pour supporter la modélisation axée sur les buts et / ou les agents.

# REDEPEND-REACT-BCN
REDEPEND-REACT est un outil qui prend en charge la modélisation i * et l'analyse des modèles résultants. Cette version étend l'outil de modélisation REDEPEND i *. L'extension se concentre sur la représentation du système d'information en utilisant le framework i * et fournit des fonctionnalités spécifiques pour la génération et l'évaluation d'architectures alternatives pour le système d'information modélisé.

# TAOM4E
TAOM4E prend en charge un développement de logiciels axé sur les modèles, axé sur les agents et en particulier sur la méthode Tropos. Il a été conçu en tenant compte des réclamations MDA (Model Driven Architecture).

# GR-Outil
Le raisonnement vers l'avant et vers l'arrière est soutenu dans Tropos par un outil de raisonnement d'objectif (GR-Outil). Fondamentalement, le GR-Tool est un outil graphique dans lequel il est possible de dessiner les modèles d'objectifs et d'exécuter les algorithmes et les outils pour le raisonnement en avant et en arrière. Les algorithmes de raisonnement avancé ont été entièrement développés en java et sont intégrés dans l'outil GR.

# Outil T
T-Tool fournit un cadre pour l'utilisation efficace des méthodes formelles dans la phase des exigences initiales. Le cadre permet l'analyse formelle et mécanisée des spécifications des exigences initiales exprimées dans un langage de modélisation formel.

# Outil ST
ST-Tool, l'outil Tropos sécurisé, est un outil graphique où il est possible de dessiner des modèles Secure Tropos et d'effectuer une analyse formelle efficace des spécifications Secure Tropos. L'outil est écrit en Java avec les composants swing et utilise XML comme format de document. L'analyse formelle est basée sur la programmation logique. ST-Tool permet à différents systèmes basés sur Datalog d'analyser la spécification Secure Tropos.





# J-PRiM
JPRiM est un outil en Java qui prend en charge PRiM, une méthodologie qui traite i * de modélisation et d'analyse d'un point de vue de Reengineering processus. J-PRiM permet d'analyser un système d'information existant et de le représenter comme une hiérarchie d'éléments i *. Une fois modélisé, plusieurs alternatives pour le système tel quel peuvent être explorées, chacune d'entre elles étant modélisée comme un modèle i * différent. Toutes les alternatives générées peuvent être évaluées en définissant et en appliquant des métriques sur les modèles i * afin d'établir quel est le plus approprié pour le système à être.

# JUCMNav
JUCMNav est un éditeur graphique pour la Notation des Utilisateurs Utilisateurs de l'UIT-T (Z.150). L'URN se compose de deux notations complémentaires: la notation de scénario de cas d'utilisation (UCM) et le langage d'exigences orienté vers le but (GRL). GRL est basé sur les frameworks i * et NFR. JUCMNav est un plug-in Eclipse qui fournit des éditeurs pour les deux notations, les liens entre les deux vues, les capacités d'analyse (y compris les évaluations de modèle GRL) et divers formats d'importation et d'exportation.

# Outil SNet
Au sein de cet outil, le formalisme i * est appliqué et étendu dans le contexte d'une méthodologie d'ingénierie des besoins pour soutenir les réseaux interorganisationnels. En particulier, l'outil fournit une transformation automatique de représentations graphiques en réseau (basé sur i * étendu) en programmes exécutables. Grâce à cela, les participants au réseau peuvent simuler différents scénarios de réseau dont les résultats peuvent donner des informations précieuses sur les risques et les avantages de la prise de certaines actions.

# Descartes
DesCARTES (Outil CASE de conception pour les dépôts, les techniques, les environnements et les systèmes orientés-agent) Architecte d'un outil d'ingénierie assistée par ordinateur (CASE) développé par l'unité de systèmes d'information (ISYS) à l'université catholique de Louvain (UCL). Elle est conçue pour prendre en charge différents modèles d'édition: modèles i * (modèles de dépendance stratégique et de rationalisation stratégique), modèles NFR, modèles UML, modèles AUML dans le contexte des développements Tropos et I-Tropos. 

 DesCARTES est un plug-in pour l'Eclipse IDE (environnement de développement intégré). L'originalité de l'outil est qu'il permet le développement de l'analyse de la méthodologie et des modèles de conception ainsi que des capacités d'ingénierie avancées et un module de gestion de projet logiciel intégré.

I * -Prefer 
est un outil qui tente d'utiliser des modèles de préférences axés sur les objectifs et sur les agents pour orienter ces activités de prise de décisions.

# IStarTool
Un éditeur graphique qui prend en charge la modélisation du système en utilisant le framework i * et exécute également l'analyse pour les modèles de ce framework.

# Measufier
Outil de définition et d'évaluation de mesures sur i * diagrammes.

# I * Modules
Une extension du plugin jUCMNav 4.2.1 qui prend en charge la définition et le fonctionnement du module.

# Les RE-Tools
Le RE-Tools est un outil de modélisation qui prend en charge le i * Framework, le Framework NFR, KAOS, Problèmes et U



# OpenOME

L'environnement de modélisation de l'organisation (OME) est un outil de modélisation et d'analyse général, orienté vers les objectifs et / ou orienté vers les agents. Il fournit aux utilisateurs une interface graphique pour développer des modèles et prend en charge l'accès à une puissante base de connaissances qui permet une analyse sophistiquée assistée par ordinateur. Cet outil est destiné à fournir aux développeurs de logiciels un lien clair entre les exigences, les spécifications et les phases de conception architecturale du développement. On s'intéresse également à l'utilisation de cet outil dans la réingénierie des processus d'affaires.

OpenOME intègre une version améliorée d'OME avec d'autres outils pour prendre en charge l'ingénierie des exigences orientée vers les buts, orientée vers les agents et orientée vers les aspects dans le développement de logiciels (Eclipse), la modélisation conceptuelle (Protégé) et d'autres environnements d'édition graphique (Visio).





Sources


http://istar.rwth-aachen.de/tiki-index.php?page=i*+Tools
http://www.cs.toronto.edu/km/openome/
